/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wJ6XtVhG9Ei
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Edu() {
  return (
    <div className="w-full min-h-screen bg-gray-100 dark:bg-gray-950">
      <header className="bg-white dark:bg-gray-900 shadow">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link className="flex items-center gap-2 text-gray-900 dark:text-gray-50" href="#">
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              Courses
            </Link>
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              Articles
            </Link>
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              Resources
            </Link>
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              About
            </Link>
          </nav>
          <div className="flex items-center gap-2">
          </div>
        </div>
      </header>
      <main className="container mx-auto px-4 py-8 md:py-12">
        <section className="mb-12">
          <h1 className="text-3xl font-bold mb-4 text-gray-900 dark:text-gray-50">Explore Our Courses</h1>
          <p className="text-gray-600 dark:text-gray-400 mb-8">
            Learn the latest skills in trading, finance, and more.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <Card>
              <img
                alt="Course Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/f1.png"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">Fundamentals of Trading</h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Learn the basics of trading and financial markets.
                </p>
                <Button size="sm">Enroll Now</Button>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Course Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/f2.png"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">
                  Advanced Portfolio Management
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Optimize your investment portfolio for maximum returns.
                </p>
                <Button size="sm">Enroll Now</Button>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Course Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/f3.png"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">
                  Cryptocurrency Trading Strategies
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Explore the world of cryptocurrency trading and investing.
                </p>
                <Button size="sm">Enroll Now</Button>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Course Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/f4.png"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">
                  Financial Modeling for Beginners
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Master the art of financial modeling and analysis.
                </p>
                <Button size="sm">Enroll Now</Button>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4 text-gray-900 dark:text-gray-50">Featured Articles</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Card>
              <img
                alt="Article Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/f5.png"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">
                  The Rise of Fintech: Disrupting Traditional Finance
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Explore how fintech is transforming the financial industry.
                </p>
                <Link
                  className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                  href="#"
                >
                  Read More
                </Link>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Article Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/f6.png"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">
                  Behavioral Finance: Understanding Investor Psychology
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Discover how human biases influence financial decision-making.
                </p>
                <Link
                  className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                  href="#"
                >
                  Read More
                </Link>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Article Image"
                className="rounded-t-lg w-full h-48 object-cover"
                height="200"
                src="/fc.jpg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">
                  The Future of Wealth Management: AI and Automation
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Explore how AI and automation are transforming wealth management.
                </p>
                <Link
                  className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                  href="#"
                >
                  Read More
                </Link>
              </CardContent>
            </Card>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4 text-gray-900 dark:text-gray-50">Useful Resources</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Card>
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">Trading Glossary</h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Understand the key terms and concepts in trading.
                </p>
                <Link
                  className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                  href="#"
                >
                  Explore Glossary
                </Link>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">Financial Calculators</h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">Utilize our suite of financial calculators.</p>
                <Link
                  className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                  href="#"
                >
                  Use Calculators
                </Link>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4">
                <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-gray-50">Market News and Analysis</h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Stay up-to-date with the latest financial news and insights.
                </p>
                <Link
                  className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                  href="#"
                >
                  Read News
                </Link>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
    </div>
  )
}

function BookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}
